course = {
    "id": "string",
    "title": "string",
    "xapiActivityId": "string",
    "created": "2024-08-21T20:04:18.708Z",
    "updated": "2024-08-21T20:04:18.708Z",
    "version": 0,
    "registrationCount": 0,
    "activityId": "string",
    "courseLearningStandard": "UNKNOWN",
    "tags": ["string"],
    "dispatched": True,
    "metadata": {
        "title": "string",
        "titleLanguage": "string",
        "description": "string",
        "descriptionLanguage": "string",
        "duration": "string",
        "typicalTime": "string",
        "keywords": ["string"],
    },
    "rootActivity": {
        "externalIdentifier": "string",
        "itemIdentifier": "string",
        "resourceIdentifier": "string",
        "activityType": "UNKNOWN",
        "href": "string",
        "scaledPassingScore": "string",
        "title": "string",
        "children": [None],
    },
}

learner = {
    "id": "string",
    "email": "string",
    "firstName": "string",
    "lastName": "string",
}

registration = {
    "id": "string",
    "instance": 0,
    "xapiRegistrationId": "string",
    "dispatchId": "string",
    "updated": "2024-08-21T20:04:18.785Z",
    "registrationCompletion": "UNKNOWN",
    "registrationCompletionAmount": 0,
    "registrationSuccess": "UNKNOWN",
    "score": {"scaled": 0},
    "totalSecondsTracked": 0,
    "firstAccessDate": "2024-08-21T20:04:18.785Z",
    "lastAccessDate": "2024-08-21T20:04:18.785Z",
    "completedDate": "2024-08-21T20:04:18.785Z",
    "createdDate": "2024-08-21T20:04:18.785Z",
    "course": {"id": "string", "title": "string", "version": 0},
    "learner": {
        "id": "string",
        "email": "string",
        "firstName": "string",
        "lastName": "string",
    },
    "tags": ["string"],
    "globalObjectives": [
        {
            "id": "string",
            "primary": True,
            "score": {"scaled": 0},
            "scoreMax": 0,
            "scoreMin": 0,
            "scoreRaw": 0,
            "previousScoreScaled": 0,
            "firstScoreScaled": 0,
            "progressMeasure": 0,
            "firstSuccessTimeStamp": "string",
            "objectiveCompletion": "UNKNOWN",
            "objectiveSuccess": "UNKNOWN",
            "previousObjectiveSuccess": "UNKNOWN",
        }
    ],
    "sharedData": [{"id": "string", "value": "string"}],
    "suspendedActivityId": "string",
    "activityDetails": {
        "id": "string",
        "title": "string",
        "attempts": 0,
        "activityCompletion": "UNKNOWN",
        "activitySuccess": "UNKNOWN",
        "score": {"scaled": 0},
        "timeTracked": "string",
        "completionAmount": {"scaled": 0},
        "suspended": True,
        "children": [None],
        "objectives": [
            {
                "id": "string",
                "primary": True,
                "score": {"scaled": 0},
                "scoreMax": 0,
                "scoreMin": 0,
                "scoreRaw": 0,
                "previousScoreScaled": 0,
                "firstScoreScaled": 0,
                "progressMeasure": 0,
                "firstSuccessTimeStamp": "string",
                "objectiveCompletion": "UNKNOWN",
                "objectiveSuccess": "UNKNOWN",
                "previousObjectiveSuccess": "UNKNOWN",
            }
        ],
        "staticProperties": {
            "completionThreshold": "string",
            "launchData": "string",
            "maxTimeAllowed": "string",
            "scaledPassingScore": 0,
            "scaledPassingScoreUsed": True,
            "timeLimitAction": "string",
        },
        "runtime": {
            "completionStatus": "string",
            "credit": "string",
            "entry": "string",
            "exit": "string",
            "learnerPreference": {
                "audioLevel": 0,
                "language": "string",
                "deliverySpeed": 0,
                "audioCaptioning": 0,
            },
            "location": "string",
            "mode": "string",
            "progressMeasure": "string",
            "scoreScaled": "string",
            "scoreRaw": "string",
            "scoreMin": "string",
            "scoreMax": "string",
            "totalTime": "string",
            "timeTracked": "string",
            "runtimeSuccessStatus": "UNKNOWN",
            "suspendData": "string",
            "learnerComments": [
                {"value": "string", "location": "string", "dateTime": "string"}
            ],
            "lmsComments": [
                {"value": "string", "location": "string", "dateTime": "string"}
            ],
            "runtimeInteractions": [
                {
                    "id": "string",
                    "type": "TrueFalse",
                    "objectives": ["string"],
                    "timestamp": "string",
                    "timestampUtc": "string",
                    "correctResponses": ["string"],
                    "weighting": "string",
                    "learnerResponse": "string",
                    "result": "string",
                    "latency": "string",
                    "description": "string",
                }
            ],
            "runtimeObjectives": [
                {
                    "id": "string",
                    "scoreScaled": "string",
                    "scoreMin": "string",
                    "scoreMax": "string",
                    "scoreRaw": "string",
                    "runtimeObjectiveSuccessStatus": "UNKNOWN",
                    "runtimeObjectiveCompletionStatus": "UNKNOWN",
                    "progressMeasure": "string",
                    "description": "string",
                }
            ],
        },
    },
}
